table Medidas
	lineageTag: cbd163e5-22f2-4e39-b142-49d024247aab

	measure 'Preço Atual' =
			
			VAR UltimaData = MAX(f_historico_ativos[Data])
			RETURN
			CALCULATE(SUM(f_historico_ativos[Close]), f_historico_ativos[Data] = UltimaData)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 1249c088-26df-4443-bd09-d7e580fc5cac

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Máxima Período' = MAXX(f_historico_ativos, f_historico_ativos[High])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 57946615-4d6a-458d-a806-337cc765f4f9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Mínima Período' = MINX(f_historico_ativos, f_historico_ativos[Low])
		lineageTag: 380ce1e1-ce56-473b-9c70-c99867476d50

	measure 'Var Diária R$' =
			
			VAR Atual = [Preço Atual]
			VAR Ontem = CALCULATE([Preço Atual], DATEADD(d_Calendario[Data], -1, DAY))
			RETURN
			IF(ISBLANK(Ontem), 0, Atual - Ontem)
		formatString: 0
		lineageTag: c2f1059b-79b4-45bd-8e41-52ee33d3dec2

	measure 'Retorno Acumulado %' =
			
			VAR PrecoInicial = CALCULATE([Preço Atual], FIRSTDATE(d_Calendario[Data]))
			VAR PrecoFinal = [Preço Atual]
			RETURN
			DIVIDE(PrecoFinal - PrecoInicial, PrecoInicial, 0)
		lineageTag: 9ffe61d8-fd11-4bdb-8f6e-e4ba7a1ba28d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ROE = ```
			
			DIVIDE(
			    SUM(f_contabilidade[Lucro_Liquido]), 
			    SUM(f_contabilidade[Patrimonio_Liquido]), 
			    0
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3552af14-c454-4e09-9cd0-2e98d31d7ab9

	measure 'Margem Líquida (Trimestral)' = ```
			
			DIVIDE(
			    SUM(f_contabilidade[Lucro_Liquido]), 
			    SUM(f_contabilidade[Receita_Liquida]), 
			    0
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6595b599-da92-4670-971c-9aa2ed4842d4

	measure EBITDA = SUM(f_contabilidade[EBITDA])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d878f238-8011-400d-96d0-7eba459b0dd3

	measure 'Dívida / EBITDA' = ```
			
			DIVIDE(
			    SUM(f_contabilidade[Divida_Total]), 
			    [EBITDA], 
			    0
			)
			```
		lineageTag: ad8eef1a-e25b-40b8-b4a9-0483afbb01e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'P/L Atual' = ```
			
			DIVIDE(
			    SUM(d_empresas[Valor_Mercado]), 
			    SUM(f_contabilidade[Lucro_Liquido]), 
			    0
			)
			```
		lineageTag: 5a2f68fe-dabc-4ba1-aa01-18253a26adf6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var %' =
			
			VAR Atual = [Preço Atual]
			VAR Ontem = CALCULATE([Preço Atual], DATEADD(d_Calendario[Data], -1, DAY))
			RETURN
			DIVIDE(Atual - Ontem, Ontem, 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6852717a-22f9-4a01-a191-b1fcc33b465c

	measure 'Volume Médio' = AVERAGE(f_historico_ativos[Volume])
		formatString: #,0
		lineageTag: e5a048e9-c42e-4a71-9019-d2e7dd728132

		annotation PBI_FormatHint = {"isDecimal":true}

	measure HTML_Logo_Centralizada = ```
			
			VAR LinkLogo = MAX(d_empresas[cc_Logo_completa_url])
			RETURN
			"<div style='
			    display: flex; 
			    justify-content: center; 
			    align-items: center; 
			    width: auto; 
			    height: auto; 
			    overflow: hidden;
			'>
			    <img src='" & LinkLogo & "' style='
			        max-width: 90%; 
			        max-height: auto; 
			        object-fit: contain;
			    '>
			</div>"
			```
		lineageTag: 95773721-2772-4e01-8af5-487d8ba47369

	column medidas
		dataType: string
		isHidden
		lineageTag: 38f106c2-5351-4760-b4a9-26c8e55e539a
		summarizeBy: none
		sourceColumn: medidas

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [medidas = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"medidas", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

